-- * ---------------------------------------------------------------------------------------------------------------- * -- 
-- * AC04 -											LINGUAGEM SQL									- [[[JUNÇÕES]]]   * --
-- *																												  * --
-- * OBJETIVO DA ATIVIDADE: FIXAR OS CONTEÚDOS SOBRE JUNÇÕES, APLICANDO CONCEITOS UTILIZADOS EM SALA DE AULA          * --
-- * ---------------------------------------------------------------------------------------------------------------- * -- 
USE PEDIDOS

-- 01. BUSCAR OS NOMES DE EMPREGADOS, COM NOMES DE CARGOS, O SALARIO ATUAL E O SALARIO INICIAL 
-- E A DIFERENCA ENTRE O SALARIO ATUAL E O SALARIO INICIAL - SUBTRAIR UM DO OUTRO (VALOR: 1,5 PONTO)
SELECT * FROM TB_EMPREGADO
SELECT * FROM TB_CARGO

SELECT	EMP.NOME, 
		EMP.SALARIO AS SALARIO_ATUAL,
		CRG.SALARIO_INIC AS SALARIO_INICIAL,
		DPT.DEPTO,
		DIFERENCA = (EMP.SALARIO - CRG.SALARIO_INIC)
FROM	TB_EMPREGADO	AS	EMP,
		TB_DEPARTAMENTO	AS	DPT,
		TB_CARGO		AS	CRG
WHERE	EMP.COD_DEPTO = DPT.COD_DEPTO 
AND		EMP.COD_CARGO = CRG.COD_CARGO

-- COM JOIN
SELECT	EMP.NOME, 
		EMP.SALARIO			AS	SALARIO_ATUAL,
		CRG.SALARIO_INIC	AS	SALARIO_INICIAL,
		DPT.DEPTO,
		DIFERENCA = (EMP.SALARIO - CRG.SALARIO_INIC)

FROM		TB_EMPREGADO		AS	EMP
INNER JOIN	TB_DEPARTAMENTO		AS	DPT
ON			EMP.COD_DEPTO = DPT.COD_DEPTO 
INNER JOIN	TB_CARGO			AS	CRG
ON			EMP.COD_CARGO = CRG.COD_CARGO

-- 02. TRAZER O NOME DE TODOS OS COLABORADORES, INDEPENDENTEMENTE DE TEREM OU NÃO DEPENDENTES. 
-- PARA OS QUE TIVEREM DEPENDENTES, TRAZER O NOME DOS DEPENDENTES TAMBÉM, PARA OS QUE NÃO TIVEREM, 
-- TRATAR O CAMPO (NOME) COM A INFORMAÇÃO "NÃO POSSUI DEPENDENTES" (VALOR: 1,5 PONTO)

SELECT		EMP.NOME,
			ISNULL (DPT.NOME, 'NÃO POSSUI DEPENDENTE') AS DEPENDENTE
FROM		TB_EMPREGADO	AS	EMP
LEFT JOIN	TB_DEPENDENTE	AS	DPT
ON			EMP.CODFUN	=	DPT.CODFUN



-- 03. TRAZER O CÓDIGO DO EMPREGADO, O NOME DO EMPREGADO E O CÓDIGO E NOME DO SEU SUPERVISOR. 
-- PARA EMPREGADOS QUE NÃO POSSUÍREM SUPERVISOR, INFORMAR "NÃO FOI ENCONTRADO SUPERIOR" NO CAMPO NOME (VALOR: 1,5 PONTO)



-- 04. 
-- A. LISTE OS CAMPOS NUM_PEDIDO, DATA_EMISSAO e VLR_TOTAL de PEDIDOS, SEGUIDOS DO NOME DO VENDEDOR
-- B. LISTE OS CAMPOS NUM_PEDIDO, DATA_EMISSAO e VLR_TOTAL de PEDIDOS, SEGUIDOS DO NOME DO CLIENTE
-- C. UNIFIQUE AS DUAS CONSULTAS ANTERIORES, OU SEJA: LISTE OS CAMPOS NUM_PEDIDO, DATA_EMISSAO e VLR_TOTAL de PEDIDOS, 
--    SEGUIDOS DO NOME DO CLIENTE E DO NOME DO VENDEDOR (VALOR: 2,0 PONTOS)

-- 05. SELECIONAR EM UMA MESMA CONSULTA, OS CARGOS EM QUE NÃO ESTÁ ALOCADO NENHUM FUNCIONÁRIO E OS FUNCIONÁRIOS QUE NÃO
-- ESTÃO ALOCADOS EM NENHUM CARGO (VALOR: 1,5 PONTO)

-- 06. SELECIONAR TODOS OS PEDIDOS (TABELA TB_PEDIDO) COM SEUS RESPECTIVOS ITENS DE PEDIDO E QUANTIDADES (TABELA TB_ITENSPEDIDO), 
-- BEM COMO O CÓDIGO E DESCRIÇÃO DOS PRODUTOS ASSOCIADOS (TB_PRODUTO)
-- FILTRAR APENAS POR PRODUTOS BRANCOS OU LARANJA (TABELA TB_COR) E COM DATA DE EMISSÃO (TABELA TB_PEDIDO) ENTRE 2012 E 2013 (VALOR: 2,0 PONTO)



-- * ---------------------------------------------------------------------------------------------------------------- * -- 
-- * AC04 -											LINGUAGEM SQL									- [[[JUNÇÕES]]]   * --
-- *																												  * --
-- *												ÓTIMA ATIVIDADE!!!											      * --
-- * ---------------------------------------------------------------------------------------------------------------- * -- 
