/*------------------------------------------------------------------------
|	V. 1.1	-	AUTOR: ANA LUIZA SAMPAIO			- DATA: 26/AGO/2021  |
|   OBJETIVO: BANCO DE DADO DA CONCESSIONARIA							 |
------------------------------------------------------------------------*/

CREATE DATABASE DB_CONCESSIONARIA

USE DB_CONCESSIONARIA



CREATE TABLE TB_ANO
( 
	ID_ANO	TINYINT IDENTITY (1,1)
,	ANO		SMALLINT				NOT NULL 

	CONSTRAINT PK_ANO PRIMARY KEY (ID_ANO)
)


CREATE TABLE TB_FABRICANTE 

( 
	ID_FABRICANTE	TINYINT IDENTITY(1,1)
,	NOME			VARCHAR(50)				NOT NULL
,	ENDERECO		VARCHAR(100)			NULL
,	CIDADE			VARCHAR(50)				NOT NULL
,	UF				CHAR(2)					NULL
,	TEL				VARCHAR(20)				NULL
,	CONTATO			VARCHAR(50)				NOT NULL

	CONSTRAINT PK_FABRICANTE PRIMARY KEY (ID_FABRICANTE)
)


CREATE TABLE TB_MES
(
	ID_MES	TINYINT IDENTITY (15,3)
,	MES		TINYINT					NOT NULL

	CONSTRAINT PK_MES PRIMARY KEY (ID_MES)
)


CREATE TABLE TB_MODELO
( 
	ID_MODELO	TINYINT IDENTITY (1,1)
,	DESCRICAO	VARCHAR(50) NOT NULL

	CONSTRAINT PK_MODELO PRIMARY KEY (ID_MODELO)
)


CREATE TABLE TB_VEICULO
( 
	ID_VEICULO		SMALLINT IDENTITY(1,1)
,	DESCRICAO		VARCHAR(50)				NOT NULL
,	VALOR			MONEY					NOT NULL
,	DATA_COMPRA		DATE					NOT NULL
,	ID_MODELO		TINYINT					NULL
,	ID_FABRICANTE	TINYINT					NULL
,	ID_ANO			TINYINT					NULL

	CONSTRAINT PK_VEICULO PRIMARY KEY (ID_VEICULO)
,	CONSTRAINT FK_VEICULO_MODELO FOREIGN KEY (ID_MODELO) REFERENCES TB_MODELO(ID_MODELO)
,	CONSTRAINT FK_VEICULO_FABRICANTE FOREIGN KEY (ID_FABRICANTE) REFERENCES TB_FABRICANTE(ID_FABRICANTE)
,	CONSTRAINT FK_VEICULO_ANO FOREIGN KEY (ID_ANO) REFERENCES TB_ANO(ID_ANO)

)

CREATE TABLE TB_VENDAS
( 
	ID_VENDAS		SMALLINT IDENTITY(1,1)
,	QUANTIDADE		SMALLINT				NOT NULL
,	ID_VEICULO		SMALLINT				NULL
,	ID_ANO			TINYINT					NULL
,	ID_MES			TINYINT					NULL

	CONSTRAINT PK_VENDAS_ANUAIS PRIMARY KEY (ID_VENDAS)
,	CONSTRAINT FK_VENDAS_ANUAIS_VEICULO FOREIGN KEY (ID_VEICULO) REFERENCES TB_VEICULO(ID_VEICULO)
,	CONSTRAINT FK_VENDAS_ANUAIS_ANO FOREIGN KEY (ID_ANO) REFERENCES TB_ANO(ID_ANO)
,	CONSTRAINT FK_VENDAS_ANUAIS_MES FOREIGN KEY (ID_MES) REFERENCES TB_MES(ID_MES)

)



select * from TB_FABRICANTE
select * from TB_MODELO
select * from TB_ANO
select * from TB_MES
select * from TB_VENDAS
select * from TB_VEICULO






