use PEDIDOS
--EXERCICIO-01 LISTAR  OS ITENS DO PEDIDO QUE POSSUAM PREÇO DE CUSTO DO PRODUTO, INFERIOR A 1 REAL
-- OBS.: TRAZER OS CAMPOS DE AMBAS AS TABELAS.
select * from TB_ITENSPEDIDO, TB_PRODUTO
where   PRECO_CUSTO > 1

--EXERCICIOS-02  SELECIONAR TODOS OS PEDIDOS E SEUS RESPECTIVOS ITENS DE PEDIDO PARA A SITUAÇÃO 'E'
-- OBS.: TRAZER OS CAMPOS DE AMBAS AS TABELAS.
select * from TB_PEDIDO, TB_ITENSPEDIDO
where     TB_PEDIDO.SITUACAO = 'E' OR TB_ITENSPEDIDO.SITUACAO = 'E'


--03SELECIONAR TODOS OS PEDIDOS, QUE POSSUAM PRODUTOS QUANTIDADE REAL SUPERIOR A 3000 
--    FILTRAR TAMBÉM PARA OS PEDIDOS QUE POSSUAM ANO DA DATA DE EMISSÃO SUPERIOR A 2010
-- OBS.: TRAZER OS CAMPOS DE AMBAS AS TABELAS
SELECT * FROM TB_PEDIDO, TB_PRODUTO
WHERE	 QTD_REAL > 3000 AND DATA_EMISSAO > 2010